language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  - luarocks install busted
  - luarocks install luasec

install:
  - luarocks make

script:
  - busted spec/okta-auth/access_spec.lua --verbose

notifications:
  email:
    on_success: never
    on_failure: never
