language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  - luarocks install kong
  - luarocks install busted
  - luarocks install lua-cjson

install:
  - make

script:
  - export LUA_PATH=$LUA_PATH;spec/fixtures/?.lua
  - busted spec/unit/access_spec.lua spec/unit/handler_spec.lua spec/unit/okta_api_spec.lua --verbose

notifications:
  email:
    on_success: never
    on_failure: never
